/**
 * @module governance/defaults
 * @description Fail-closed fallback configuration for degraded mode.
 *
 * SECURITY: When Supabase is unreachable, we degrade to maintenance mode.
 * - ALL feature flags OFF (except enable_maintenance_mode)
 * - ALL plan limits ZERO
 * - No commerce transactions, no user registration, no feature access
 *
 * This prevents unpaid feature access during outages.
 *
 * @locked 🔴 CANONICAL — ecommerce-template/packages/shared is the source of truth.
 */

import type { AppConfig } from './schemas'

// Validated at test-time via AppConfigSchema.parse(FALLBACK_CONFIG)
export const FALLBACK_CONFIG: AppConfig = {
    config: {
        id: 'fallback',
        tenant_id: null,
        business_name: 'Store',
        whatsapp_number: '',
        default_country_prefix: '1',
        primary_color: '#2D5016',
        secondary_color: '#8BC34A',
        accent_color: '#FF9800',
        surface_color: '#FAFDF6',
        text_color: '#1A2E0A',
        color_preset: 'nature',
        theme_mode: 'light',
        logo_url: null,
        language: 'en',
        timezone: 'UTC',
        meta_title: null,
        meta_description: null,
        favicon_url: null,
        hero_title: null,
        hero_subtitle: null,
        hero_image: null,
        footer_description: null,
        active_languages: ['en'],
        active_currencies: ['usd'],
        default_currency: 'usd',
        store_email: null,
        store_phone: null,
        store_address: null,
        social_facebook: null,
        social_instagram: null,
        social_tiktok: null,
        social_twitter: null,
        announcement_bar_text: null,
        announcement_bar_enabled: false,
        min_order_amount: 0,
        max_delivery_radius_km: null,
        business_hours: null,
        delivery_info_text: null,
        bank_name: null,
        bank_account_type: null,
        bank_account_number: null,
        bank_account_holder: null,
        bank_id_number: null,
        google_analytics_id: null,
        facebook_pixel_id: null,
        sentry_dsn: null,
        custom_css: null,
        stock_mode: 'always_in_stock',
        low_stock_threshold: 5,
        free_shipping_threshold: 0,
        tax_display_mode: 'tax_included',
        onboarding_completed: false,
        // Gamification defaults
        achievements_unlocked: [],
        dismissed_tips: [],
        checklist_skipped: false,
        tour_completed: false,
        panel_language: null,
        storefront_language: null,
    },
    featureFlags: {
        // RESTRICTIVE DEFAULTS — all optional features OFF during degradation
        enable_whatsapp_checkout: false,
        enable_online_payments: false,
        enable_cash_on_delivery: false,
        enable_bank_transfer: false,
        enable_whatsapp_contact: false,
        enable_user_registration: false,
        enable_guest_checkout: false,
        require_auth_to_order: false,
        enable_google_auth: false,
        enable_email_auth: false,
        enable_ecommerce: false,
        enable_reviews: false,
        enable_wishlist: false,
        enable_carousel: false,
        enable_cms_pages: false,
        enable_product_search: false,
        enable_related_products: false,
        enable_product_comparisons: false,
        enable_product_badges: false,
        enable_analytics: false,
        enable_promotions: false,
        enable_multi_language: false,
        enable_multi_currency: false,
        enable_admin_api: false,
        enable_social_links: false,
        enable_order_notes: false,
        enable_address_management: false,
        enable_newsletter: false,
        // ONLY maintenance mode enabled — safest posture during outage
        enable_maintenance_mode: true,
        enable_owner_panel: false,
        enable_customer_accounts: false,
        enable_order_tracking: false,
        enable_cookie_consent: false,
        enable_chatbot: false,
        enable_self_service_returns: false,
        owner_lite_enabled: false,
        owner_advanced_modules_enabled: false,
        enable_crm: false,
        enable_crm_segmentation: false,
        enable_crm_export: false,
        enable_email_notifications: false,
        enable_abandoned_cart_emails: false,
        enable_email_campaigns: false,
        enable_email_templates: false,
    },
    planLimits: {
        // MINIMUM VALUES — no capacity granted during degradation
        max_products: 0,
        max_customers: 0,
        max_orders_month: 0,
        max_categories: 0,
        max_images_per_product: 0,
        max_cms_pages: 0,
        max_carousel_slides: 0,
        max_admin_users: 0,
        storage_limit_mb: 0,
        plan_name: 'degraded',
        plan_expires_at: null,
        max_languages: 1,
        max_currencies: 1,
        max_whatsapp_templates: 0,
        max_file_upload_mb: 0,
        max_email_sends_month: 0,
        max_custom_domains: 0,
        max_chatbot_messages_month: 0,
        max_badges: 0,
        max_newsletter_subscribers: 0,
        max_requests_day: 0,
        max_reviews_per_product: 0,
        max_wishlist_items: 0,
        max_promotions_active: 0,
        max_payment_methods: 0,
        max_crm_contacts: 0,
    },
    planExpired: false,
    tenantStatus: 'active',
    _degraded: true,
}
