/**
 * Governance Contract Types & Data
 *
 * Imports the governance-contract.json from the workspace root.
 * This file exists to provide clean imports and type safety.
 *
 * Source: ../../../../../../../../governance-contract.json
 * Generated by: BOOTANDSTRAP_WEB/scripts/generate-contract.ts
 */

// Use require for JSON located outside the TS include path
// eslint-disable-next-line @typescript-eslint/no-require-imports
const contract = require('../../../../../../../../governance-contract.json') as GovernanceContract

export interface GovernanceContract {
    $schema: string
    generated_at: string
    generated_by: string
    flags: {
        count: number
        keys: string[]
        groups: Record<string, {
            label: string
            color: string
            flags: string[]
        }>
    }
    limits: {
        count: number
        keys: string[]
        numeric_keys: string[]
        metadata_keys: string[]
    }
    modules: {
        count: number
        keys: string[]
        catalog: ModuleCatalogEntry[]
    }
    pricing: {
        maintenance_chf_month: number
        web_base_chf_onetime: number
    }
    config_aliases: Record<string, string>
}

export interface ModuleCatalogEntry {
    key: string
    name: string
    icon: string
    description: string
    category: string
    popular: boolean
    requires: string[]
    tiers: ModuleTierEntry[]
}

export interface ModuleTierEntry {
    key: string
    name: string
    price_chf: number
    features: string[]
    recommended: boolean
}

export default contract
