/**
 * Config Schema Alignment Tests
 *
 * Verifies that the TypeScript interfaces in config.ts match the governance
 * contract generated by BSWEB. If a flag is added to flag-hierarchy.ts but not
 * to the storefront FeatureFlags interface (or vice-versa), these tests catch it.
 *
 * Source of truth: ../governance-contract.json
 * Generated by:   BOOTANDSTRAP_WEB/scripts/generate-contract.ts
 */
import { describe, it, expect, vi as _vi, beforeEach, afterEach } from 'vitest'
import type { FeatureFlags, PlanLimits, StoreConfig } from '../config'
import { getRequiredTenantId } from '../config'

// ---------------------------------------------------------------------------
// Governance Contract — single source of truth for expected keys
// ---------------------------------------------------------------------------
import contract from '../governance-contract.json'

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe('Config Schema Alignment (Governance Contract)', () => {
    describe('FeatureFlags interface', () => {
        it(`has exactly ${contract.flags.count} flags (matches governance contract)`, () => {
            // Build a dummy object with all interface keys to count them at runtime
            const dummyFlags: Record<keyof FeatureFlags, boolean> = {
                // Checkout
                enable_whatsapp_checkout: true,
                enable_online_payments: true,
                enable_cash_on_delivery: true,
                enable_bank_transfer: true,
                enable_whatsapp_contact: true,
                enable_guest_checkout: true,
                require_auth_to_order: true,
                enable_order_notes: true,
                enable_promotions: true,
                enable_ecommerce: true,
                // Auth
                enable_user_registration: true,
                enable_email_auth: true,
                enable_google_auth: true,
                enable_customer_accounts: true,
                enable_address_management: true,
                enable_order_tracking: true,
                // Content
                enable_carousel: true,
                enable_cms_pages: true,
                enable_product_search: true,
                enable_reviews: true,
                enable_wishlist: true,
                enable_related_products: true,
                enable_product_comparisons: true,
                enable_product_badges: true,
                // i18n
                enable_multi_language: true,
                enable_multi_currency: true,
                // Business
                enable_social_links: true,
                enable_owner_panel: true,
                enable_newsletter: true,
                // System
                enable_analytics: true,
                enable_admin_api: true,
                enable_maintenance_mode: true,
                enable_cookie_consent: true,
                enable_chatbot: true,
                enable_self_service_returns: true,
                owner_lite_enabled: true,
                owner_advanced_modules_enabled: false,
                // CRM
                enable_crm: true,
                enable_crm_segmentation: true,
                enable_crm_export: true,
                // Email Marketing
                enable_email_notifications: true,
                enable_abandoned_cart_emails: true,
                enable_email_campaigns: true,
                enable_email_templates: true,
                // POS
                enable_pos: true,
                enable_pos_kiosk: true,
                enable_pos_keyboard_shortcuts: true,
                enable_pos_quick_sale: true,
                enable_pos_offline_cart: true,
                enable_pos_thermal_printer: true,
                enable_pos_line_discounts: true,
                enable_pos_customer_search: true,
                enable_pos_multi_device: true,
                enable_pos_shifts: true,
                // Capacidad
                enable_traffic_expansion: true,
                enable_traffic_analytics: true,
                enable_traffic_autoscale: true,
                // New module gates (Phase 4)
                enable_seo: true,
                enable_social_media: true,
                enable_automations: true,
                enable_auth_advanced: true,
                enable_sales_channels: true,
            }

            const interfaceKeys = Object.keys(dummyFlags).sort()
            const contractKeys = [...contract.flags.keys].sort()

            // Count must match
            expect(interfaceKeys.length).toBe(contract.flags.count)

            // Every contract flag must exist in the interface
            for (const key of contractKeys) {
                expect(interfaceKeys).toContain(key)
            }

            // Every interface flag must exist in the contract
            for (const key of interfaceKeys) {
                expect(contractKeys).toContain(key)
            }
        })

        it('all flag values are booleans', () => {
            for (const flag of contract.flags.keys) {
                expect(typeof flag).toBe('string')
            }
        })
    })

    describe('PlanLimits interface', () => {
        it(`has exactly ${contract.limits.count} limit keys (matches governance contract)`, () => {
            const dummyLimits: PlanLimits = {
                max_products: 100,
                max_customers: 100,
                max_orders_month: 500,
                max_categories: 20,
                max_images_per_product: 10,
                max_cms_pages: 10,
                max_carousel_slides: 10,
                max_admin_users: 3,
                storage_limit_mb: 500,
                plan_name: 'starter',
                plan_tier: null,
                plan_expires_at: null,
                max_languages: 1,
                max_currencies: 1,
                max_whatsapp_templates: 5,
                max_file_upload_mb: 5,
                max_email_sends_month: 500,
                max_custom_domains: 1,
                max_chatbot_messages_month: 200,
                max_badges: 3,
                max_newsletter_subscribers: 100,
                max_requests_day: 5000,
                max_reviews_per_product: 50,
                max_wishlist_items: 100,
                max_promotions_active: 5,
                max_payment_methods: 3,
                max_pos_payment_methods: 3,
                max_crm_contacts: 200,
            }

            const interfaceKeys = Object.keys(dummyLimits).sort()
            // Contract has 27 keys but PlanLimits may not have plan_tier (it's governance metadata)
            // We compare against all contract limit keys that exist in the interface
            const contractKeys = [...contract.limits.keys].sort()

            // Every interface limit must be in the contract
            for (const key of interfaceKeys) {
                expect(contractKeys).toContain(key)
            }

            // Every numeric limit from contract must be in the interface
            for (const key of contract.limits.numeric_keys) {
                expect(interfaceKeys).toContain(key)
            }
        })
    })

    describe('StoreConfig interface', () => {
        it('includes tenant_id for multi-tenant support', () => {
            const dummy: StoreConfig = {} as StoreConfig
            // Type-level check — if tenant_id doesn't exist this won't compile
            const _idCheck: string | null = dummy.tenant_id
            expect(true).toBe(true) // Passes if compilation succeeds
        })

        it('includes Phase 8A columns', () => {
            const dummy: StoreConfig = {} as StoreConfig
            // These should all exist on the interface
            const _checks: (string | null)[] = [
                dummy.store_email,
                dummy.store_phone,
                dummy.store_address,
                dummy.social_facebook,
                dummy.social_instagram,
                dummy.social_tiktok,
                dummy.social_twitter,
                dummy.announcement_bar_text,
                dummy.bank_name,
                dummy.bank_account_type,
                dummy.bank_account_number,
                dummy.bank_account_holder,
                dummy.bank_id_number,
                dummy.google_analytics_id,
                dummy.facebook_pixel_id,
                dummy.custom_css,
                dummy.delivery_info_text,
            ]
            expect(true).toBe(true)
        })
    })

    describe('Governance Contract integrity', () => {
        it('contract has expected structure', () => {
            expect(contract.$schema).toBe('governance-contract/v1')
            expect(contract.flags.count).toBeGreaterThanOrEqual(43)
            expect(contract.limits.count).toBeGreaterThanOrEqual(27)
            expect(contract.modules.count).toBeGreaterThanOrEqual(10)
        })

        it('module keys are all canonical', () => {
            const expectedModules = [
                'auth_advanced', 'automation', 'capacidad', 'chatbot', 'crm',
                'ecommerce', 'email_marketing', 'i18n', 'pos', 'rrss',
                'sales_channels', 'seo',
            ]
            expect(contract.modules.keys.sort()).toEqual(expectedModules.sort())
        })

        it('every module has at least one tier', () => {
            for (const mod of contract.modules.catalog) {
                expect(mod.tiers.length).toBeGreaterThanOrEqual(1)
            }
        })
    })
})

// ---------------------------------------------------------------------------
// getRequiredTenantId() tests
// ---------------------------------------------------------------------------

describe('getRequiredTenantId', () => {
    const originalEnv = process.env

    beforeEach(() => {
        process.env = { ...originalEnv }
        // Clear both vars
        delete process.env.TENANT_ID
        delete process.env.NEXT_PUBLIC_TENANT_ID
    })

    afterEach(() => {
        process.env = originalEnv
    })

    it('returns TENANT_ID when set', () => {
        process.env.TENANT_ID = 'tenant-abc'
        expect(getRequiredTenantId()).toBe('tenant-abc')
    })

    it('does NOT fall back to NEXT_PUBLIC_TENANT_ID (server-only contract)', () => {
        process.env.NEXT_PUBLIC_TENANT_ID = 'tenant-xyz'
            // Without TENANT_ID set, should NOT use NEXT_PUBLIC_TENANT_ID
            ; (process.env as Record<string, string | undefined>).NODE_ENV = 'development'
        const result = getRequiredTenantId()
        expect(result).toBe('__dev_no_tenant__')
        // Must NOT return the public tenant id
        expect(result).not.toBe('tenant-xyz')
    })

    it('prefers TENANT_ID (ignores NEXT_PUBLIC_TENANT_ID entirely)', () => {
        process.env.TENANT_ID = 'private-id'
        process.env.NEXT_PUBLIC_TENANT_ID = 'public-id'
        expect(getRequiredTenantId()).toBe('private-id')
    })

    it('throws in production when neither env var is set', () => {
        (process.env as Record<string, string | undefined>).NODE_ENV = 'production'
        expect(() => getRequiredTenantId()).toThrow('[FATAL] TENANT_ID is not set in production')
    })

    it('throws in production even if NEXT_PUBLIC_TENANT_ID is set (not a valid server fallback)', () => {
        (process.env as Record<string, string | undefined>).NODE_ENV = 'production'
        process.env.NEXT_PUBLIC_TENANT_ID = 'public-id'
        expect(() => getRequiredTenantId()).toThrow('[FATAL] TENANT_ID is not set in production')
    })

    it('returns dev placeholder in development when neither env var is set', () => {
        (process.env as Record<string, string | undefined>).NODE_ENV = 'development'
        expect(getRequiredTenantId()).toBe('__dev_no_tenant__')
    })
})
