import {
    createStep,
    createWorkflow,
    WorkflowResponse,
    StepResponse,
    transform,
} from "@medusajs/framework/workflows-sdk"

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

type ProvisionStoreInput = {
    /** Tenant identifier from governance layer */
    tenant_id: string
    /** Store admin email */
    admin_email: string
    /** Admin password (auto-generated by provisioner) */
    admin_password: string
    /** Default region country (ISO alpha-2) */
    country_code: string
    /** Default currency (ISO 4217) */
    currency_code: string
    /** Business name for the store */
    store_name: string
    /** Whether to seed demo products */
    seed_demo: boolean
}

type ProvisionStoreOutput = {
    tenant_id: string
    admin_created: boolean
    region_id: string | null
    sales_channel_id: string | null
    publishable_key: string | null
    products_seeded: number
}

// ---------------------------------------------------------------------------
// Step 1: Create Admin User (idempotent — ignores "already exists")
// ---------------------------------------------------------------------------

const createAdminStep = createStep(
    "provision-create-admin",
    async (input: { email: string; password: string }, { container }) => {
        const userModule = container.resolve("user")

        try {
            // Check if admin already exists
            const [existing] = await userModule.listUsers({ email: input.email })
            if (existing) {
                console.log(
                    JSON.stringify({
                        level: "info",
                        event: "provision.admin_exists",
                        email: input.email,
                    })
                )
                return new StepResponse(
                    { created: false, user_id: existing.id },
                    { user_id: existing.id }
                )
            }

            // Create via authModule for proper password hashing
            const authModule = container.resolve("auth")
            const authIdentity = await authModule.createAuthIdentities({
                provider_identities: [{
                    provider: "emailpass",
                    entity_id: input.email,
                    provider_metadata: { password: input.password },
                }]
            })

            const user = await userModule.createUsers({
                email: input.email,
            })

            // Link auth identity to user
            const remoteLink = container.resolve("remoteLink")
            await remoteLink.create({
                user: { user_id: user.id },
                auth: { auth_identity_id: authIdentity.id },
            })

            console.log(
                JSON.stringify({
                    level: "info",
                    event: "provision.admin_created",
                    email: input.email,
                    user_id: user.id,
                })
            )

            return new StepResponse(
                { created: true, user_id: user.id },
                { user_id: user.id }
            )
        } catch (err) {
            // Idempotent: if admin exists, that's fine
            const msg = err instanceof Error ? err.message : String(err)
            if (msg.includes("already exists") || msg.includes("duplicate")) {
                return new StepResponse(
                    { created: false, user_id: "unknown" },
                    { user_id: "unknown" }
                )
            }
            throw err
        }
    },
    async (compensationData) => {
        if (!compensationData?.user_id) return
        console.warn(
            JSON.stringify({
                level: "warn",
                event: "provision.admin_create.compensation",
                user_id: compensationData.user_id,
                message: "Admin user creation requires manual cleanup",
            })
        )
    }
)

// ---------------------------------------------------------------------------
// Step 2: Create Default Region
// ---------------------------------------------------------------------------

const createRegionStep = createStep(
    "provision-create-region",
    async (
        input: { country_code: string; currency_code: string; store_name: string },
        { container }
    ) => {
        const regionModule = container.resolve("region")

        // Check for existing regions
        const existing = await regionModule.listRegions({})
        if (existing.length > 0) {
            console.log(
                JSON.stringify({
                    level: "info",
                    event: "provision.region_exists",
                    region_id: existing[0].id,
                })
            )
            return new StepResponse(
                { region_id: existing[0].id, created: false },
                null
            )
        }

        const region = await regionModule.createRegions({
            name: `${input.store_name} Region`,
            currency_code: input.currency_code.toLowerCase(),
            countries: [input.country_code.toLowerCase()],
            automatic_taxes: true,
        })

        console.log(
            JSON.stringify({
                level: "info",
                event: "provision.region_created",
                region_id: region.id,
                currency: input.currency_code,
                country: input.country_code,
            })
        )

        return new StepResponse(
            { region_id: region.id, created: true },
            { region_id: region.id }
        )
    },
    async (compensationData, { container }) => {
        if (!compensationData?.region_id) return
        try {
            const regionModule = container.resolve("region")
            await regionModule.deleteRegions(compensationData.region_id)
        } catch { /* cleanup best-effort */ }
    }
)

// ---------------------------------------------------------------------------
// Step 3: Create Default Sales Channel
// ---------------------------------------------------------------------------

const createSalesChannelStep = createStep(
    "provision-create-sales-channel",
    async (input: { store_name: string }, { container }) => {
        const salesChannelModule = container.resolve("sales_channel")

        const existing = await salesChannelModule.listSalesChannels({})
        if (existing.length > 0) {
            return new StepResponse(
                { sales_channel_id: existing[0].id, created: false },
                null
            )
        }

        const sc = await salesChannelModule.createSalesChannels({
            name: `${input.store_name} Storefront`,
            description: `Default sales channel for ${input.store_name}`,
            is_disabled: false,
        })

        console.log(
            JSON.stringify({
                level: "info",
                event: "provision.sales_channel_created",
                sales_channel_id: sc.id,
            })
        )

        return new StepResponse(
            { sales_channel_id: sc.id, created: true },
            { sales_channel_id: sc.id }
        )
    },
    async (compensationData, { container }) => {
        if (!compensationData?.sales_channel_id) return
        try {
            const salesChannelModule = container.resolve("sales_channel")
            await salesChannelModule.deleteSalesChannels(compensationData.sales_channel_id)
        } catch { /* cleanup best-effort */ }
    }
)

// ---------------------------------------------------------------------------
// Step 4: Create Publishable API Key
// ---------------------------------------------------------------------------

const createPublishableKeyStep = createStep(
    "provision-create-publishable-key",
    async (
        input: { store_name: string; sales_channel_id: string | null },
        { container }
    ) => {
        const apiKeyModule = container.resolve("api_key")

        const existing = await apiKeyModule.listApiKeys({ type: "publishable" })
        if (existing.length > 0) {
            return new StepResponse(
                { key: existing[0].token, created: false },
                null
            )
        }

        const key = await apiKeyModule.createApiKeys({
            title: `${input.store_name} Publishable Key`,
            type: "publishable",
            created_by: "system",
        })

        // Link to sales channel
        if (input.sales_channel_id) {
            try {
                const remoteLink = container.resolve("remoteLink")
                await remoteLink.create({
                    api_key: { api_key_id: key.id },
                    sales_channel: { sales_channel_id: input.sales_channel_id },
                })
            } catch (err) {
                console.warn(
                    JSON.stringify({
                        level: "warn",
                        event: "provision.link_key_channel_failed",
                        error: err instanceof Error ? err.message : String(err),
                    })
                )
            }
        }

        console.log(
            JSON.stringify({
                level: "info",
                event: "provision.publishable_key_created",
                key_id: key.id,
            })
        )

        return new StepResponse(
            { key: key.token, created: true },
            { key_id: key.id }
        )
    },
    async (compensationData, { container }) => {
        if (!compensationData?.key_id) return
        try {
            const apiKeyModule = container.resolve("api_key")
            await apiKeyModule.deleteApiKeys(compensationData.key_id)
        } catch { /* cleanup best-effort */ }
    }
)

// ---------------------------------------------------------------------------
// Step 5: Seed Demo Products (conditional)
// ---------------------------------------------------------------------------

const seedDemoProductsStep = createStep(
    "provision-seed-demo-products",
    async (input: { seed: boolean; region_id: string | null }, { container }) => {
        if (!input.seed || !input.region_id) {
            return new StepResponse({ count: 0 })
        }

        const productModule = container.resolve("product")

        // Check if products already exist
        const existingCount = await productModule.listProducts({})
        if (existingCount.length > 0) {
            console.log(
                JSON.stringify({
                    level: "info",
                    event: "provision.seed_skipped",
                    reason: "products_exist",
                    count: existingCount.length,
                })
            )
            return new StepResponse({ count: existingCount.length })
        }

        // Create a minimal demo product set
        const demoProducts = [
            { title: "Demo Product", description: "Sample product for testing", status: "published" as const },
        ]

        let created = 0
        for (const prod of demoProducts) {
            try {
                await productModule.createProducts(prod)
                created++
            } catch {
                // Skip on error
            }
        }

        console.log(
            JSON.stringify({
                level: "info",
                event: "provision.seed_complete",
                products_created: created,
            })
        )

        return new StepResponse({ count: created })
    }
)

// ---------------------------------------------------------------------------
// Step 6: Notify storefront of provisioning completion
// ---------------------------------------------------------------------------

const notifyProvisioningCompleteStep = createStep(
    "provision-notify-complete",
    async (input: { tenant_id: string; publishable_key: string | null }) => {
        const storefrontUrl = process.env.STOREFRONT_URL || "http://localhost:3000"
        const eventsSecret = process.env.MEDUSA_EVENTS_SECRET || ""

        try {
            const res = await fetch(`${storefrontUrl}/api/webhooks/medusa-events`, {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                    ...(eventsSecret && { "x-medusa-events-secret": eventsSecret }),
                },
                body: JSON.stringify({
                    event_type: "store.provisioned",
                    data: {
                        tenant_id: input.tenant_id,
                        publishable_key: input.publishable_key,
                    },
                }),
                signal: AbortSignal.timeout(10000),
            })

            return new StepResponse({ notified: res.ok })
        } catch {
            // Non-fatal: provisioning succeeded even if notification fails
            return new StepResponse({ notified: false })
        }
    }
)

// ---------------------------------------------------------------------------
// Workflow: Provision Store
// ---------------------------------------------------------------------------

const provisionStoreWorkflow = createWorkflow(
    "provision-store",
    (input: ProvisionStoreInput) => {
        // Step 1: Create admin user
        const adminResult = createAdminStep({
            email: input.admin_email,
            password: input.admin_password,
        })

        // Step 2: Create default region
        const regionResult = createRegionStep({
            country_code: input.country_code,
            currency_code: input.currency_code,
            store_name: input.store_name,
        })

        // Step 3: Create sales channel
        const salesChannelResult = createSalesChannelStep({
            store_name: input.store_name,
        })

        // Step 4: Create publishable key (needs sales channel ID)
        const keyInput = transform(
            { salesChannelResult, storeName: input.store_name },
            (data) => ({
                store_name: data.storeName,
                sales_channel_id: data.salesChannelResult.sales_channel_id,
            })
        )
        const keyResult = createPublishableKeyStep(keyInput)

        // Step 5: Seed demo products (conditional)
        const seedInput = transform(
            { regionResult, seedDemo: input.seed_demo },
            (data) => ({
                seed: data.seedDemo,
                region_id: data.regionResult.region_id,
            })
        )
        const seedResult = seedDemoProductsStep(seedInput)

        // Step 6: Notify storefront
        const notifyInput = transform(
            { keyResult, tenantId: input.tenant_id },
            (data) => ({
                tenant_id: data.tenantId,
                publishable_key: data.keyResult.key,
            })
        )
        const notifyResult = notifyProvisioningCompleteStep(notifyInput)

        // Build final result
        const result = transform(
            { adminResult, regionResult, salesChannelResult, keyResult, seedResult, tenantId: input.tenant_id },
            (data): ProvisionStoreOutput => ({
                tenant_id: data.tenantId,
                admin_created: data.adminResult.created,
                region_id: data.regionResult.region_id,
                sales_channel_id: data.salesChannelResult.sales_channel_id,
                publishable_key: data.keyResult.key,
                products_seeded: data.seedResult.count,
            })
        )

        return new WorkflowResponse(result)
    }
)

export default provisionStoreWorkflow
