#!/usr/bin/env tsx
/**
 * seed-demo.ts — SOTA Local Demo Seeder
 *
 * Rewritten 2026-03-24 to replicate BSWEB/seed-business-data.ts pattern.
 * Clean → Categories → Products → Customers → Orders → Governance.
 *
 * Uses the fresh-produce template data (20 products, 6 categories) inlined
 * from BSWEB/industry-templates.ts (cross-repo import not possible).
 *
 * Usage:
 *   npx tsx scripts/seed-demo.ts                  # Standard seed (clean + products + orders + gov)
 *   npx tsx scripts/seed-demo.ts --full             # Full seed (+ carousel, pages, promos, chatbot, newsletter)
 *   npx tsx scripts/seed-demo.ts --clean-only     # Just wipe products (no re-seed)
 *   npx tsx scripts/seed-demo.ts --skip-orders    # Seed products but skip orders
 *   npx tsx scripts/seed-demo.ts --template=fashion  # (future: different template)
 */

import * as fs from 'fs'
import * as path from 'path'

// ── Load .env ────────────────────────────────────────────────

const envPath = path.resolve(__dirname, '../.env')
if (fs.existsSync(envPath)) {
    for (const line of fs.readFileSync(envPath, 'utf-8').split('\n')) {
        const trimmed = line.trim()
        if (!trimmed || trimmed.startsWith('#')) continue
        const eqIdx = trimmed.indexOf('=')
        if (eqIdx === -1) continue
        const key = trimmed.slice(0, eqIdx).trim()
        const val = trimmed.slice(eqIdx + 1).trim()
        if (!process.env[key]) process.env[key] = val
    }
}

// ── Types (mirroring industry-templates.ts) ──────────────────

interface CategoryDef {
    name: string
    handle: string
    description: string
}

interface VariantDef {
    title: string
    sku: string
    prices: Array<{ amount: number; currency_code: string }>
}

interface ProductDef {
    title: string
    handle: string
    description: string
    category: string
    variants: VariantDef[]
    weight?: number
    thumbnail?: string
}

interface DemoTemplate {
    id: string
    name: string
    storeName: string
    categories: CategoryDef[]
    products: ProductDef[]
}

// ── Load uploaded image URLs (generated by seed-campifruit-images.ts) ─

function loadImageUrls(): Record<string, string> {
    const mapPath = path.resolve(__dirname, 'campifruit-image-urls.json')
    if (fs.existsSync(mapPath)) {
        return JSON.parse(fs.readFileSync(mapPath, 'utf-8'))
    }
    return {}
}

function img(slug: string): string | undefined {
    const urls = loadImageUrls()
    return urls[slug] || undefined
}

// ── Fresh-Produce Template (generic) ─────────────────────────

const FRESH_PRODUCE: DemoTemplate = {
    id: 'fresh-produce',
    name: 'Frutas y Verduras',
    storeName: 'Frutas Frescas del Campo',
    categories: [
        { name: 'Frutas Frescas', handle: 'frutas-frescas', description: 'Frutas de temporada recién recolectadas' },
        { name: 'Verduras', handle: 'verduras', description: 'Verduras frescas del huerto' },
        { name: 'Cestas y Packs', handle: 'cestas-packs', description: 'Cestas variadas y packs familiares' },
        { name: 'Productos Artesanos', handle: 'artesanos', description: 'Mermeladas, aceites y conservas artesanales' },
        { name: 'Frutos Secos', handle: 'frutos-secos', description: 'Frutos secos y semillas seleccionados' },
        { name: 'Lácteos y Huevos', handle: 'lacteos-huevos', description: 'Lácteos frescos y huevos de corral' },
    ],
    products: [
        {
            title: 'Naranjas Valencia', handle: 'naranjas-valencia',
            description: 'Naranjas dulces de Valencia, ideales para zumo y mesa.',
            category: 'frutas-frescas', weight: 5000,
            thumbnail: 'https://images.unsplash.com/photo-1547514701-42782101795e?w=800&q=80&fit=crop',
            variants: [
                { title: '5 kg', sku: 'NAR-VAL-5', prices: [{ amount: 1290, currency_code: 'eur' }, { amount: 1390, currency_code: 'usd' }] },
                { title: '10 kg', sku: 'NAR-VAL-10', prices: [{ amount: 2190, currency_code: 'eur' }, { amount: 2390, currency_code: 'usd' }] },
            ],
        },
    ],
}

// ── Campifruit Template (real client — COP) ──────────────────
// Precios en COP (pesos colombianos). Medusa almacena en la unidad
// más pequeña; COP no tiene centavos, así que amount = pesos directos.

const CAMPIFRUIT: DemoTemplate = {
    id: 'campifruit',
    name: 'Campifruit — Frutas Frescas',
    storeName: 'Campifruit',
    categories: [
        { name: 'Fresas', handle: 'fresas', description: 'Fresas frescas seleccionadas del campo' },
        { name: 'Moras', handle: 'moras', description: 'Moras frescas de cultivo artesanal' },
        { name: 'Brevas', handle: 'brevas', description: 'Brevas frescas de temporada' },
        { name: 'Duraznos', handle: 'duraznos', description: 'Duraznos madurados en la finca' },
        { name: 'Piña', handle: 'pina', description: 'Piña gold fresca — entera, en rodajas, cubos y trozos' },
        { name: 'Elaborados', handle: 'elaborados', description: 'Glasés, mermeladas y conservas artesanales de frutas' },
    ],
    products: [
        // ── FRESAS ──
        {
            title: 'Fresa Fresca', handle: 'fresa-fresca',
            description: 'Fresas frescas seleccionadas del campo, cultivadas con esmero para garantizar su dulzura y aroma natural.',
            category: 'fresas', weight: 500,
            thumbnail: img('fresa-fresca'),
            variants: [
                { title: 'Tarrina 250g', sku: 'CF-FRE-250', prices: [{ amount: 6500, currency_code: 'cop' }, { amount: 150, currency_code: 'usd' }] },
                { title: 'Tarrina 500g', sku: 'CF-FRE-500', prices: [{ amount: 11900, currency_code: 'cop' }, { amount: 275, currency_code: 'usd' }] },
            ],
        },
        // ── MORAS ──
        {
            title: 'Mora Fresca', handle: 'mora-fresca',
            description: 'Moras frescas de cultivo artesanal, ricas en antioxidantes y con un sabor intenso y equilibrado.',
            category: 'moras', weight: 500,
            thumbnail: img('mora-250g'),
            variants: [
                { title: 'Tarrina 250g', sku: 'CF-MOR-250', prices: [{ amount: 5500, currency_code: 'cop' }, { amount: 130, currency_code: 'usd' }] },
                { title: 'Tarrina 500g', sku: 'CF-MOR-500', prices: [{ amount: 9900, currency_code: 'cop' }, { amount: 230, currency_code: 'usd' }] },
            ],
        },
        // ── BREVAS ──
        {
            title: 'Breva Fresca', handle: 'breva-fresca',
            description: 'Brevas frescas de temporada, suaves y dulces. Un fruto delicado seleccionado en su punto óptimo.',
            category: 'brevas', weight: 1000,
            thumbnail: img('breva-fresca'),
            variants: [
                { title: 'Tarrina 250g', sku: 'CF-BRE-250', prices: [{ amount: 7900, currency_code: 'cop' }, { amount: 185, currency_code: 'usd' }] },
                { title: 'Tarrina 500g', sku: 'CF-BRE-500', prices: [{ amount: 13900, currency_code: 'cop' }, { amount: 325, currency_code: 'usd' }] },
                { title: 'Tarrina 1kg', sku: 'CF-BRE-1K', prices: [{ amount: 24900, currency_code: 'cop' }, { amount: 580, currency_code: 'usd' }] },
            ],
        },
        // ── DURAZNOS ──
        {
            title: 'Durazno Fresco', handle: 'durazno-fresco',
            description: 'Duraznos madurados en la finca, jugosos y aromáticos. Seleccionados uno a uno.',
            category: 'duraznos', weight: 500,
            thumbnail: img('durazno-fresco'),
            variants: [
                { title: 'Tarrina 250g', sku: 'CF-DUR-250', prices: [{ amount: 6900, currency_code: 'cop' }, { amount: 160, currency_code: 'usd' }] },
                { title: 'Tarrina 500g', sku: 'CF-DUR-500', prices: [{ amount: 11900, currency_code: 'cop' }, { amount: 275, currency_code: 'usd' }] },
            ],
        },
        // ── PIÑA ──
        {
            title: 'Piña Entera', handle: 'pina-entera',
            description: 'Piña gold fresca, cosechada en su punto ideal de maduración. Dulce y jugosa.',
            category: 'pina', weight: 2000,
            thumbnail: img('pina-entera'),
            variants: [
                { title: 'Unidad (~2kg)', sku: 'CF-PIN-UNI', prices: [{ amount: 8900, currency_code: 'cop' }, { amount: 210, currency_code: 'usd' }] },
            ],
        },
        {
            title: 'Piña en Rodajas', handle: 'pina-rodajas',
            description: 'Piña cortada en rodajas uniformes, lista para servir. Ideal para postres y ensaladas.',
            category: 'pina', weight: 1000,
            thumbnail: img('pina-rodajas'),
            variants: [
                { title: 'Bandeja 250g', sku: 'CF-PIN-ROD-250', prices: [{ amount: 6900, currency_code: 'cop' }, { amount: 160, currency_code: 'usd' }] },
                { title: 'Bandeja 1kg', sku: 'CF-PIN-ROD-1K', prices: [{ amount: 19900, currency_code: 'cop' }, { amount: 465, currency_code: 'usd' }] },
            ],
        },
        {
            title: 'Piña en Cubos', handle: 'pina-cubos',
            description: 'Cubos de piña fresca cortados a mano. Perfectos para batidos, ensaladas y snacks.',
            category: 'pina', weight: 1000,
            thumbnail: img('pina-cubos'),
            variants: [
                { title: 'Bandeja 250g', sku: 'CF-PIN-CUB-250', prices: [{ amount: 6900, currency_code: 'cop' }, { amount: 160, currency_code: 'usd' }] },
                { title: 'Bandeja 1kg', sku: 'CF-PIN-CUB-1K', prices: [{ amount: 19900, currency_code: 'cop' }, { amount: 465, currency_code: 'usd' }] },
            ],
        },
        {
            title: 'Piña en Trozos', handle: 'pina-trozos',
            description: 'Trozos irregulares de piña fresca. Ideales para cocinar, jugos naturales y conservas.',
            category: 'pina', weight: 1000,
            thumbnail: img('pina-trozos'),
            variants: [
                { title: 'Bandeja 250g', sku: 'CF-PIN-TRZ-250', prices: [{ amount: 5900, currency_code: 'cop' }, { amount: 140, currency_code: 'usd' }] },
                { title: 'Bandeja 1kg', sku: 'CF-PIN-TRZ-1K', prices: [{ amount: 16900, currency_code: 'cop' }, { amount: 395, currency_code: 'usd' }] },
            ],
        },
        // ── ELABORADOS ──
        {
            title: 'Glasé de Fresa', handle: 'glase-fresa',
            description: 'Glasé artesanal de fresa elaborado con frutas frescas de nuestra finca. Textura suave y sabor intenso.',
            category: 'elaborados', weight: 500,
            thumbnail: img('glase-fresa'),
            variants: [
                { title: 'Tarro 500g', sku: 'CF-GLA-FRE', prices: [{ amount: 12900, currency_code: 'cop' }, { amount: 300, currency_code: 'usd' }] },
            ],
        },
        {
            title: 'Glasé de Mora', handle: 'glase-mora',
            description: 'Glasé artesanal de mora con el sabor concentrado de moras frescas del campo.',
            category: 'elaborados', weight: 500,
            thumbnail: img('glase-mora'),
            variants: [
                { title: 'Tarro 500g', sku: 'CF-GLA-MOR', prices: [{ amount: 12900, currency_code: 'cop' }, { amount: 300, currency_code: 'usd' }] },
            ],
        },
        {
            title: 'Mermelada de Mora', handle: 'mermelada-mora',
            description: 'Mermelada artesanal de mora elaborada con receta tradicional. Sin conservantes artificiales.',
            category: 'elaborados', weight: 500,
            thumbnail: img('mermelada-mora'),
            variants: [
                { title: 'Tarro 500g', sku: 'CF-MER-MOR', prices: [{ amount: 9900, currency_code: 'cop' }, { amount: 230, currency_code: 'usd' }] },
            ],
        },
    ],
}

// ── Demo Customers ──────────────────────────────────────────

const DEMO_CUSTOMERS = [
    { first: 'María', last: 'García López', email: 'demo-customer-1@bootandstrap.demo' },
    { first: 'Carlos', last: 'Martínez Ruiz', email: 'demo-customer-2@bootandstrap.demo' },
    { first: 'Laura', last: 'Fernández Torres', email: 'demo-customer-3@bootandstrap.demo' },
    { first: 'Pablo', last: 'Sánchez Moreno', email: 'demo-customer-4@bootandstrap.demo' },
    { first: 'Ana', last: 'Rodríguez Jiménez', email: 'demo-customer-5@bootandstrap.demo' },
    { first: 'Javier', last: 'López Hernández', email: 'demo-customer-6@bootandstrap.demo' },
    { first: 'Elena', last: 'Navarro Castro', email: 'demo-customer-7@bootandstrap.demo' },
    { first: 'Diego', last: 'Romero Ortiz', email: 'demo-customer-8@bootandstrap.demo' },
    { first: 'Lucía', last: 'Domínguez Ruiz', email: 'demo-customer-9@bootandstrap.demo' },
    { first: 'Andrés', last: 'Molina Gil', email: 'demo-customer-10@bootandstrap.demo' },
    { first: 'Isabel', last: 'Serrano Blanco', email: 'demo-customer-11@bootandstrap.demo' },
    { first: 'Tomás', last: 'Ramírez Peña', email: 'demo-customer-12@bootandstrap.demo' },
]

// ── Template Registry ────────────────────────────────────────

const TEMPLATES: Record<string, DemoTemplate> = {
    'fresh-produce': FRESH_PRODUCE,
    'campifruit': CAMPIFRUIT,
}

// ── Medusa API Client ────────────────────────────────────────

class MedusaClient {
    private jwt = ''
    constructor(private readonly baseUrl: string) {}

    async login(email: string, password: string): Promise<void> {
        const res = await this.request<{ token?: string }>('/auth/user/emailpass', {
            body: { email, password },
        })
        if (!res.token) throw new Error('Medusa login failed — no token returned')
        this.jwt = res.token
    }

    async request<T = any>(
        endpoint: string,
        options: { method?: string; body?: object } = {}
    ): Promise<T> {
        const res = await fetch(`${this.baseUrl}${endpoint}`, {
            method: options.method ?? (options.body ? 'POST' : 'GET'),
            headers: {
                'Content-Type': 'application/json',
                ...(this.jwt ? { 'Authorization': `Bearer ${this.jwt}` } : {}),
            },
            ...(options.body && { body: JSON.stringify(options.body) }),
            signal: AbortSignal.timeout(30_000),
        })

        if (!res.ok) {
            const text = await res.text().catch(() => '')
            if (res.status === 409) return { _conflict: true } as T
            throw new Error(`Medusa ${res.status} ${endpoint}: ${text.slice(0, 300)}`)
        }
        if (res.status === 204) return {} as T
        return res.json()
    }
}

// ── Logger ───────────────────────────────────────────────────

function log(icon: string, msg: string) {
    console.log(`  ${icon} ${msg}`)
}

// ── Step 1: Clean Existing Data ──────────────────────────────

async function cleanExistingData(client: MedusaClient): Promise<void> {
    log('🧹', 'Cleaning existing data...')

    // Delete all products first (FK → categories)
    let deletedProducts = 0
    try {
        const { products } = await client.request<{ products: Array<{ id: string; title: string }> }>(
            '/admin/products?limit=100&fields=id,title'
        )
        if (products?.length) {
            for (const p of products) {
                try {
                    await client.request(`/admin/products/${p.id}`, { method: 'DELETE' })
                    deletedProducts++
                } catch { /* skip individual errors */ }
            }
            log('🧹', `Deleted ${deletedProducts}/${products.length} products`)
        }
    } catch (err) {
        log('⚠️', `Product cleanup: ${err instanceof Error ? err.message : err}`)
    }

    // Delete all categories
    let deletedCategories = 0
    try {
        const { product_categories } = await client.request<{ product_categories: Array<{ id: string; name: string }> }>(
            '/admin/product-categories?limit=100&fields=id,name'
        )
        if (product_categories?.length) {
            for (const c of product_categories) {
                try {
                    await client.request(`/admin/product-categories/${c.id}`, { method: 'DELETE' })
                    deletedCategories++
                } catch { /* may have children */ }
            }
            log('🧹', `Deleted ${deletedCategories}/${product_categories.length} categories`)
        }
    } catch (err) {
        log('⚠️', `Category cleanup: ${err instanceof Error ? err.message : err}`)
    }

    if (deletedProducts === 0 && deletedCategories === 0) {
        log('✅', 'No stale data — fresh Medusa instance')
    }
}

// ── Step 2: Seed Categories ──────────────────────────────────

const categoryIdCache = new Map<string, string>()

async function seedCategories(client: MedusaClient, categories: CategoryDef[]): Promise<number> {
    let created = 0
    for (const cat of categories) {
        try {
            const { product_category } = await client.request<{ product_category: { id: string } }>(
                '/admin/product-categories',
                { body: { name: cat.name, handle: cat.handle, description: cat.description, is_active: true, is_internal: false } }
            )
            categoryIdCache.set(cat.handle, product_category.id)
            created++
            log('✅', `Category: ${cat.name}`)
        } catch {
            // Already exists — look up
            const { product_categories } = await client.request<{ product_categories: Array<{ id: string; handle: string }> }>(
                `/admin/product-categories?handle=${cat.handle}`
            )
            if (product_categories?.[0]) {
                categoryIdCache.set(cat.handle, product_categories[0].id)
                log('⏭️', `Category: ${cat.name} (existing)`)
            }
        }
    }
    return created
}

// ── Step 3: Seed Products ────────────────────────────────────

async function seedProducts(client: MedusaClient, template: DemoTemplate, salesChannelId: string): Promise<number> {
    let created = 0

    for (const prod of template.products) {
        // Check if already exists
        const { products: existing } = await client.request<{ products: Array<{ id: string; thumbnail: string | null }> }>(
            `/admin/products?handle=${prod.handle}`
        )
        if (existing?.length) {
            // Update thumbnail if missing
            if (prod.thumbnail && !existing[0].thumbnail) {
                try {
                    await client.request(`/admin/products/${existing[0].id}`, {
                        body: { thumbnail: prod.thumbnail, images: [{ url: prod.thumbnail }] },
                    })
                    log('📸', `${prod.title} (updated thumbnail)`)
                } catch {
                    log('⏭️', `${prod.title} (existing)`)
                }
            } else {
                log('⏭️', `${prod.title} (existing)`)
            }
            continue
        }

        try {
            const categoryId = categoryIdCache.get(prod.category)
            await client.request('/admin/products', {
                body: {
                    title: prod.title,
                    handle: prod.handle,
                    description: prod.description,
                    status: 'published',
                    weight: prod.weight,
                    ...(prod.thumbnail ? { thumbnail: prod.thumbnail, images: [{ url: prod.thumbnail }] } : {}),
                    ...(categoryId ? { categories: [{ id: categoryId }] } : {}),
                    sales_channels: [{ id: salesChannelId }],
                    options: [{ title: 'Tamaño', values: prod.variants.map(v => v.title) }],
                    variants: prod.variants.map(v => ({
                        title: v.title,
                        sku: v.sku,
                        manage_inventory: false,
                        prices: v.prices,
                        options: { 'Tamaño': v.title },
                    })),
                },
            })
            created++
            log('✅', `${prod.title} (${prod.variants.length} variants)`)
        } catch (err) {
            log('⚠️', `${prod.title}: ${err instanceof Error ? err.message : err}`)
        }
    }

    return created
}

// ── Step 4: Seed Demo Customers ──────────────────────────────

async function seedCustomers(client: MedusaClient): Promise<number> {
    let created = 0

    for (const cust of DEMO_CUSTOMERS) {
        try {
            const { customers } = await client.request<{ customers: Array<{ id: string; email: string }> }>(
                `/admin/customers?q=${cust.email}`
            )
            if (customers?.find(c => c.email === cust.email)) {
                log('⏭️', `Customer: ${cust.first} ${cust.last} (existing)`)
                continue
            }

            await client.request('/admin/customers', {
                body: { email: cust.email, first_name: cust.first, last_name: cust.last },
            })
            created++
            log('✅', `Customer: ${cust.first} ${cust.last}`)
        } catch (err) {
            log('⚠️', `Customer ${cust.first}: ${err instanceof Error ? err.message : err}`)
        }
    }

    return created
}

// ── Step 5: Seed Demo Orders ─────────────────────────────────

async function seedOrders(client: MedusaClient, regionId: string, count: number = 10): Promise<number> {
    // Fetch products + variants for order items
    const { products } = await client.request<{
        products: Array<{
            id: string
            title: string
            variants: Array<{ id: string; title: string }>
        }>
    }>('/admin/products?limit=50')

    if (!products?.length) {
        log('⚠️', 'No products available — cannot create orders')
        return 0
    }

    // Fetch customers
    const { customers } = await client.request<{
        customers: Array<{ id: string; email: string }>
    }>('/admin/customers?limit=20')

    let created = 0
    const now = Date.now()

    for (let i = 0; i < count; i++) {
        try {
            // Pick random product and variant
            const product = products[Math.floor(Math.random() * products.length)]
            const variant = product.variants?.[Math.floor(Math.random() * (product.variants?.length || 1))]
            if (!variant) continue

            // Pick random customer (or fallback email)
            const customer = customers?.length
                ? customers[Math.floor(Math.random() * customers.length)]
                : null

            // Spread orders over last 30 days
            const daysAgo = Math.floor(Math.random() * 30)
            const orderDate = new Date(now - daysAgo * 86_400_000)

            const { draft_order } = await client.request<{ draft_order: { id: string } }>(
                '/admin/draft-orders',
                {
                    body: {
                        region_id: regionId,
                        ...(customer ? { customer_id: customer.id } : {
                            email: `order-${i + 1}@demo.local`,
                        }),
                        items: [{
                            variant_id: variant.id,
                            quantity: Math.floor(Math.random() * 3) + 1,
                        }],
                        shipping_methods: [],
                        metadata: {
                            demo_seed: true,
                            seed_date: orderDate.toISOString(),
                            seed_index: i,
                        },
                    },
                }
            )

            if (draft_order?.id) {
                created++
                if (created % 5 === 0 || created === count) {
                    log('✅', `Orders: ${created}/${count} created`)
                }
            }
        } catch (err) {
            log('⚠️', `Order #${i + 1}: ${err instanceof Error ? err.message : err}`)
        }
    }

    return created
}

// ── Step 6: Stock Location Setup ─────────────────────────────

async function ensureStockLocation(client: MedusaClient, salesChannelId: string): Promise<string | undefined> {
    try {
        const { stock_locations } = await client.request<{ stock_locations: Array<{ id: string }> }>('/admin/stock-locations')
        let stockLocationId = stock_locations?.[0]?.id

        if (!stockLocationId) {
            const { stock_location } = await client.request<{ stock_location: { id: string } }>('/admin/stock-locations', {
                body: { name: 'Almacén Principal', address: { country_code: 'es' } },
            })
            stockLocationId = stock_location?.id
            log('✅', `Stock location created: ${stockLocationId}`)
        } else {
            log('✅', `Stock location: ${stockLocationId}`)
        }

        // Link to sales channel (idempotent)
        if (stockLocationId) {
            await client.request(`/admin/stock-locations/${stockLocationId}/sales-channels`, {
                body: { add: [salesChannelId] },
            })
            log('✅', 'Stock location linked to sales channel')
        }

        return stockLocationId
    } catch (err) {
        log('⚠️', `Stock location: ${err instanceof Error ? err.message : err}`)
        return undefined
    }
}
// ── Step 7: Ensure Regions for all currencies in the template ──

const CURRENCY_REGION_MAP: Record<string, { name: string; countries: string[] }> = {
    cop: { name: 'Colombia', countries: ['co'] },
    usd: { name: 'United States', countries: ['us'] },
    eur: { name: 'Europe', countries: ['es', 'de', 'fr', 'it'] },
    chf: { name: 'Switzerland', countries: ['ch'] },
}

async function ensureRegionsForTemplate(client: MedusaClient, template: DemoTemplate): Promise<string> {
    // Collect all unique currency codes from all products
    const currencies = new Set<string>()
    for (const prod of template.products) {
        for (const v of prod.variants) {
            for (const p of v.prices) {
                currencies.add(p.currency_code)
            }
        }
    }

    log('🌍', `Template uses ${currencies.size} currencies: ${[...currencies].join(', ')}`)

    const { regions } = await client.request<{ regions: Array<{ id: string; name: string; currency_code: string }> }>('/admin/regions')
    let primaryRegionId = ''

    for (const currency of currencies) {
        const existing = regions?.find(r => r.currency_code === currency)
        if (existing) {
            log('✅', `Region for ${currency.toUpperCase()}: ${existing.name} (${existing.id})`)
            if (!primaryRegionId) primaryRegionId = existing.id
            continue
        }

        const regionDef = CURRENCY_REGION_MAP[currency]
        if (!regionDef) {
            log('⚠️', `No region mapping for ${currency.toUpperCase()} — skipping`)
            continue
        }

        try {
            const { region } = await client.request<{ region: { id: string } }>('/admin/regions', {
                body: {
                    name: regionDef.name,
                    currency_code: currency,
                    countries: regionDef.countries,
                    automatic_taxes: true,
                },
            })
            log('✅', `Region created: ${regionDef.name}/${currency.toUpperCase()} (${region.id})`)
            if (!primaryRegionId) primaryRegionId = region.id
        } catch (err) {
            log('⚠️', `Region ${currency}: ${err instanceof Error ? err.message : err}`)
        }
    }

    if (!primaryRegionId) {
        // Fallback
        const fallback = regions?.[0]?.id
        if (fallback) return fallback
        throw new Error('No region available')
    }

    return primaryRegionId
}

// ══════════════════════════════════════════════════════════════
// MAIN
// ══════════════════════════════════════════════════════════════

async function main() {
    const args = process.argv.slice(2)
    const cleanOnly = args.includes('--clean-only')
    const skipOrders = args.includes('--skip-orders')
    const fullSeed = args.includes('--full')
    const templateArg = args.find(a => a.startsWith('--template='))?.split('=')[1] || 'campifruit'

    const template = TEMPLATES[templateArg]
    if (!template) {
        console.error(`❌ Unknown template: "${templateArg}". Available: ${Object.keys(TEMPLATES).join(', ')}`)
        process.exit(1)
    }

    const MEDUSA_URL = process.env.MEDUSA_ADMIN_URL || process.env.MEDUSA_URL || 'http://localhost:9000'
    const ADMIN_EMAIL = process.env.MEDUSA_ADMIN_EMAIL || 'admin@medusa-test.com'
    const ADMIN_PASSWORD = process.env.MEDUSA_ADMIN_PASSWORD || 'supersecret'
    const TENANT_ID = process.env.TENANT_ID || ''

    console.log('')
    console.log('═══════════════════════════════════════════════════════════════')
    console.log(`  🌱 DEMO SEEDER — ${template.name}`)
    console.log('═══════════════════════════════════════════════════════════════')
    console.log(`  Template:   ${template.id} (${template.products.length} products, ${template.categories.length} categories)`)
    console.log(`  Medusa:     ${MEDUSA_URL}`)
    console.log(`  Mode:       ${cleanOnly ? 'CLEAN ONLY' : skipOrders ? 'PRODUCTS ONLY' : fullSeed ? 'FULL (products + orders + content)' : 'STANDARD (products + orders)'}`)
    if (TENANT_ID) console.log(`  Tenant:     ${TENANT_ID}`)
    console.log('')

    const startTime = performance.now()
    const client = new MedusaClient(MEDUSA_URL)

    // ── Login ──
    log('🔑', `Logging into Medusa...`)
    try {
        await client.login(ADMIN_EMAIL, ADMIN_PASSWORD)
        log('✅', 'Authenticated')
    } catch (err) {
        log('❌', `Login failed: ${err instanceof Error ? err.message : err}`)
        log('💡', 'Make sure Medusa is running and admin user exists')
        process.exit(1)
    }

    // ── Clean ──
    await cleanExistingData(client)
    if (cleanOnly) {
        const elapsed = Math.round(performance.now() - startTime)
        console.log(`\n  ✅ Clean complete (${elapsed}ms)`)
        return
    }

    // ── Store Config ──
    const { stores } = await client.request<{ stores: Array<{ id: string }> }>('/admin/stores')
    const storeId = stores?.[0]?.id
    if (storeId) {
        await client.request(`/admin/stores/${storeId}`, {
            method: 'POST',
            body: { name: template.storeName },
        })
        log('✅', `Store name: "${template.storeName}"`)
    }

    // ── Sales Channel ──
    const { sales_channels } = await client.request<{ sales_channels: Array<{ id: string }> }>('/admin/sales-channels')
    const salesChannelId = sales_channels?.[0]?.id
    if (!salesChannelId) {
        log('❌', 'No sales channel found — Medusa not fully initialized')
        process.exit(1)
    }
    log('✅', `Sales channel: ${salesChannelId}`)

    // ── Regions (auto-create for all currencies in template) ──
    const regionId = await ensureRegionsForTemplate(client, template)
    log('✅', `Primary region: ${regionId}`)

    // ── Stock Location ──
    await ensureStockLocation(client, salesChannelId)

    // ── Seed Categories ──
    console.log('\n  ── Categories ──')
    const categoriesSeeded = await seedCategories(client, template.categories)

    // ── Seed Products ──
    console.log('\n  ── Products ──')
    const productsSeeded = await seedProducts(client, template, salesChannelId)

    // ── Seed Customers ──
    let customersSeeded = 0
    if (!skipOrders) {
        console.log('\n  ── Customers ──')
        customersSeeded = await seedCustomers(client)
    }

    // ── Seed Orders ──
    let ordersSeeded = 0
    if (!skipOrders) {
        console.log('\n  ── Orders ──')
        ordersSeeded = await seedOrders(client, regionId, 25)
    }

    // ── Governance ──
    // seedGovernance is self-sufficient: auto-provisions tenant if TENANT_ID is missing
    console.log('\n  ── Governance ──')
    try {
        const { seedGovernance } = require('./seed-governance')
        const effectiveTenantId = await seedGovernance(TENANT_ID || null, template.id, log)
        if (effectiveTenantId && !TENANT_ID) {
            log('📝', `TENANT_ID auto-provisioned: ${effectiveTenantId}`)
            log('💡', 'Written to .env — restart storefront to pick it up')
        }
    } catch (err) {
        log('⚠️', `Governance: ${err instanceof Error ? err.message : err}`)
    }

    // ── Content (carousel, CMS, promos, chatbot, newsletter) ──
    let contentSeeded = false
    if (fullSeed && TENANT_ID) {
        console.log('\n  ── Content ──')
        try {
            const { seedContent } = require('./seed-content')
            await seedContent(TENANT_ID, template.id, undefined, log)
            contentSeeded = true
        } catch (err) {
            log('⚠️', `Content: ${err instanceof Error ? err.message : err}`)
        }
    }

    // ── Summary ──
    const elapsed = Math.round(performance.now() - startTime)
    console.log('')
    console.log('═══════════════════════════════════════════════════════════════')
    console.log(`  🎉 DEMO SEED COMPLETE`)
    console.log('═══════════════════════════════════════════════════════════════')
    console.log(`  Template:     ${template.name} (${template.id})`)
    console.log(`  Categories:   ${categoriesSeeded} created, ${template.categories.length} total`)
    console.log(`  Products:     ${productsSeeded} created, ${template.products.length} total`)
    console.log(`  Customers:    ${customersSeeded} created`)
    console.log(`  Orders:       ${ordersSeeded} created`)
    if (fullSeed) console.log(`  Content:      ${contentSeeded ? '✅ carousel + pages + promos + chatbot + newsletter' : '⚠️ skipped (no TENANT_ID)'}`)
    console.log(`  Time:         ${elapsed}ms (${(elapsed / 1000).toFixed(1)}s)`)
    console.log('')
    console.log('  📋 Next steps:')
    console.log('     1. Open storefront:  http://localhost:3000/es')
    console.log('     2. Owner panel:      http://localhost:3000/es/panel')
    console.log('     3. POS:              http://localhost:3000/es/panel/pos')
    console.log('═══════════════════════════════════════════════════════════════')
}

main().catch(err => {
    console.error('❌ Fatal error:', err)
    process.exit(1)
})
