-- ============================================================================
-- Governance Realtime Broadcast Trigger
-- Generated by bns-gov CLI — Phase 4
--
-- Purpose: When any governance table changes (feature_flags, plan_limits,
-- capability_overrides, config, module_orders), broadcast an invalidation
-- signal to the storefront via Supabase Realtime.
--
-- The storefront's useRealtimeGovernance hook listens on
-- `governance:{tenant_id}` channel and calls router.refresh() to re-fetch
-- config from the server.
--
-- Prerequisites:
--   1. Supabase Realtime must be enabled for the project
--   2. supabase_realtime extension must be available
-- ============================================================================

-- ── Trigger Function ───────────────────────────────────────────────────────
-- Uses realtime.send() to broadcast a "governance_change" event.
-- Channel name: "governance:{tenant_id}"
-- Payload: just enough metadata for debugging (table, op, timestamp)
-- Data is NOT sent — the storefront re-fetches via existing RPC pipeline.

CREATE OR REPLACE FUNCTION broadcast_governance_change()
RETURNS trigger AS $$
DECLARE
    v_tenant_id uuid;
BEGIN
    -- Extract tenant_id from the affected row
    v_tenant_id := COALESCE(NEW.tenant_id, OLD.tenant_id);
    
    IF v_tenant_id IS NULL THEN
        RETURN COALESCE(NEW, OLD);
    END IF;

    -- Broadcast invalidation signal via Supabase Realtime
    -- realtime.send(channel, event, payload, is_public)
    BEGIN
        PERFORM realtime.send(
            'governance:' || v_tenant_id::text,
            'governance_change',
            jsonb_build_object(
                'table', TG_TABLE_NAME,
                'operation', TG_OP,
                'tenant_id', v_tenant_id::text,
                'ts', extract(epoch from now())
            ),
            true  -- public channel (anon key can subscribe)
        );
    EXCEPTION WHEN OTHERS THEN
        -- Silently ignore if realtime.send() is not available
        -- This prevents the trigger from blocking writes if Realtime is down
        RAISE WARNING 'broadcast_governance_change: realtime.send() failed: %', SQLERRM;
    END;

    RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ── Attach triggers to governance tables ───────────────────────────────────

-- Feature flags
DROP TRIGGER IF EXISTS trg_broadcast_feature_flags ON feature_flags;
CREATE TRIGGER trg_broadcast_feature_flags
    AFTER INSERT OR UPDATE ON feature_flags
    FOR EACH ROW EXECUTE FUNCTION broadcast_governance_change();

-- Plan limits
DROP TRIGGER IF EXISTS trg_broadcast_plan_limits ON plan_limits;
CREATE TRIGGER trg_broadcast_plan_limits
    AFTER INSERT OR UPDATE ON plan_limits
    FOR EACH ROW EXECUTE FUNCTION broadcast_governance_change();

-- Config
DROP TRIGGER IF EXISTS trg_broadcast_config ON config;
CREATE TRIGGER trg_broadcast_config
    AFTER INSERT OR UPDATE ON config
    FOR EACH ROW EXECUTE FUNCTION broadcast_governance_change();

-- Capability overrides
DROP TRIGGER IF EXISTS trg_broadcast_capability_overrides ON capability_overrides;
CREATE TRIGGER trg_broadcast_capability_overrides
    AFTER INSERT OR UPDATE OR DELETE ON capability_overrides
    FOR EACH ROW EXECUTE FUNCTION broadcast_governance_change();

-- Module orders (active module changes)
DROP TRIGGER IF EXISTS trg_broadcast_module_orders ON module_orders;
CREATE TRIGGER trg_broadcast_module_orders
    AFTER INSERT OR UPDATE ON module_orders
    FOR EACH ROW EXECUTE FUNCTION broadcast_governance_change();
