-- ============================================================
-- Custom Email Domain Support (Ruta B — Enterprise Feature)
-- ============================================================
-- Compatibility stub only.
--
-- The canonical DDL for config.custom_email_domain* lives in:
--   - BOOTANDSTRAP_WEB control-plane ground truth
--   - this repo's legacy 001_schema_core.sql squash
--
-- Keeping the post-cutoff migration empty avoids introducing fresh
-- control-plane DDL in the data-plane repo while preserving migration history.
